name: extraapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
   assets:
     - assets/images/

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_bluetooth_serial: ^0.2.2
  scoped_model: ^1.0.1
  dropdown_formfield: ^0.1.2
  photo_view: ^0.9.2
  flutter_svprogresshud: ^0.0.3
  web_socket_channel: ^2.0.0
  rxdart: ^0.23.1
  http: ^0.12.0+3
  socket_io_client: ^0.9.7+2
  firebase_core: "0.7.0"
  firebase_auth: "^0.20.1"
  provider: ^4.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
